# Generated by Django 6.1 on 2026-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-start_date']},
        ),
        migrations.RemoveField(
            model_name='education',
            name='title',
        ),
        migrations.AddField(
            model_name='education',
            name='accomplishments',
            field=models.TextField(blank=True, help_text='Key achievements, honors, GPA, relevant coursework, etc.'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_or_title',
            field=models.CharField(default='', help_text='e.g., Bachelor of Science in Computer Science', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if currently pursuing', null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(default='', help_text='Name of School, College, or University', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if you are currently studying here'),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of study', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='about',
            field=models.TextField(blank=True, help_text='Brief summary or description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
    ]
