# Generated by Django 6.1 on 2026-09-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_education_options_remove_education_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-start_date']},
        ),
        migrations.AddField(
            model_name='experience',
            name='company_name',
            field=models.CharField(blank=True, help_text='Name of the company or organization', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if currently working here', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check if you currently work here'),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date of employment', null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(help_text='e.g., Software Developer', max_length=200),
        ),
    ]
