# Generated by Django 6.1 on 2026-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_experience_options_experience_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Hackathon Organizer', max_length=200)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, help_text='e.g., 2024 - 2025', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text='e.g., Senior Developer at TechCorp', max_length=255)),
                ('contact_info', models.CharField(blank=True, help_text='Email or LinkedIn profile', max_length=255)),
                ('quote', models.TextField(blank=True, help_text='What they said about you')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
