# Generated by Django 6.1 on 2026-09-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_extracurricular_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='e.g., Django, PostgreSQL, Tailwind CSS', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='tools_used',
            field=models.CharField(blank=True, help_text='e.g., Git, PyCharm, LangChain', max_length=255),
        ),
    ]
