# Generated by Django 6.1 on 2026-09-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_tech_stack_project_tools_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone',
        ),
    ]
