# Generated by Django 6.1 on 2026-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_sitesetting_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Your long profile picture for the homepage', null=True, upload_to='site/'),
        ),
    ]
