# Generated by Django 6.1 on 2026-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_sitesetting_email_sitesetting_linkedin_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name', max_length=200)),
                ('logo', models.ImageField(upload_to='companies/')),
                ('link', models.URLField(blank=True, help_text='Optional link to the company website', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['order'],
            },
        ),
    ]
